### ISSUE TITLE
New Feature Request...

### ISSUE THREAD

**Issue by mansoorhaq** [zk4/m3u8_dl#16]
Hi,
First of all thanks for a great tool.
I would like to request a feature that will download the best available video resolution.

Currently, the tool is downloading the video but it is only downloading the lower quality video, unless I am missing something.
The reason I know this as I downloaded the same video using [IDM](https://www.internetdownloadmanager.com/) and I got high resolution video every time.

If possible, please consider adding this in your next release.

**Comment by zk4** [comment]
I think it's related to concating url paramters. No universal solution for that.  PR would be appreaciated.
