### ISSUE TITLE
error when installing pycrypto

### ISSUE THREAD

**Issue by SolSolis** [zk4/m3u8_dl#6]
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

After Microsoft Visual C++ 14.0 is installed, 

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by zk4** [comment]
I don`t know why cl.exe  has anything to do with m3u8_dl. Maybe you shoud describe your problem more accurate in process .

**Comment by ZimingYuan** [comment]
I also met an issue when I installed pycrypto. I fixed it by installing a library called pycrytodome instead. Then download the source of m3_dl, modify the pycrypto and the version number in requirements.txt, and then run "python setup.py install" to install from the source.

**Comment by zk4** [comment]
> I also met an issue when I installed pycrypto. I fixed it by installing a library called pycrytodome instead. Then download the source of m3_dl, modify the pycrypto and the version number in requirements.txt, and then run "python setup.py install" to install from the source.

A PR would be appreciated.
