### ISSUE TITLE
Can you support referencing in python scripts?

### ISSUE THREAD

**Issue by xwyrz** [zk4/m3u8_dl#7]
I want to use it in python files, not the command line.

**Comment by zk4** [comment]
@snow922841 
There is no callback or anything exposed api for now.
you could call it with os.popen from python code.

**Comment by xwyrz** [comment]
Thank you for your reply. 

I want to report another question. 

When using m3-dl on Windows, the progress emoji cannot be displayed normally.

**Comment by zk4** [comment]
@snow922841  
https://github.com/zk4/m3u8_dl/blob/9b6de83fdd850c191831f422a74329e9f6951817/m3_dl/D.py#L14
change this function as you like.

**Comment by zk4** [comment]
you can import it as normal package.
